version: '3'

services:
  minio1:
    image: minio/minio
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
      - "9096:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --address ":9000" --console-address ":9090" http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    networks:
      - minio_distributed

  minio2:
    image: minio/minio
    volumes:
      - data2:/data
    ports:
      - "9002:9000"
      - "9097:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --address ":9000" --console-address ":9090" http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    networks:
      - minio_distributed

  minio3:
    image: minio/minio
    volumes:
      - data3:/data
    ports:
      - "9003:9000"
      - "9098:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --address ":9000" --console-address ":9090" http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    networks:
      - minio_distributed

  minio4:
    image: minio/minio
    volumes:
      - data4:/data
    ports:
      - "9004:9000"
      - "9099:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --address ":9000" --console-address ":9090" http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    networks:
      - minio_distributed

volumes:
  data1:
  data2:
  data3:
  data4:

networks:
  minio_distributed:
    driver: bridge
